#!/bin/bash

export PATH="$(realpath ..):$PATH"

spacemouse-event | {
    while read EVENT; do
        if ! grep -q 'device: ' <<<"${EVENT}"; then
            continue
        fi
        device=$(sed -rn 's/device: ([^ ]*?) .*/\1/p' <<<"${EVENT}")
        if ! grep -q 'disconnect'<<<"${EVENT}"; then
            echo "spacemouse-led -d ${device} on"
            spacemouse-led -d "${device}" on
        fi
    done
}
